name: Linux, gcc, gnu-efi

on: 
  push:
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**.cmd'
      - '!set_grub_cpu.cmd'
      - '**.md'
      - '**.sh'
      - '!set_grub_cpu.sh'
      - '**.txt'
      - '**.vbs'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**.cmd'
      - '!set_grub_cpu.cmd'
      - '**.md'
      - '**.sh'
      - '!set_grub_cpu.sh'
      - '**.txt'
      - '**.vbs'

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        arch: [x64, ia32, aa64, arm, riscv64, loongarch64]
        include:
        - arch: x64
          pkg: gcc-mingw-w64-x86-64
          tuple: x86_64-w64-mingw32-
        - arch: ia32
          pkg: gcc-mingw-w64-i686
          tuple: i686-w64-mingw32-
        - arch: aa64
          pkg: gcc-aarch64-linux-gnu
          tuple: aarch64-linux-gnu-
        - arch: arm
          pkg: gcc-arm-linux-gnueabi
          tuple: arm-linux-gnueabi-
        - arch: riscv64
          pkg: gcc-riscv64-linux-gnu
          tuple: riscv64-linux-gnu-
        - arch: loongarch64
          pkg: gcc-multilib
          tuple: loongarch64-unknown-linux-gnu-

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install gcc toolchain
      run: |
        sudo apt-get update
        sudo apt-get install ${{ matrix.pkg }}
        if [[ "${{ matrix.arch }}" == "loongarch64" ]]; then
          curl -L -O https://github.com/loongson/build-tools/releases/download/2024.11.01/x86_64-cross-tools-loongarch64-binutils_2.43.1-gcc_14.2.0-glibc_2.40.tar.xz
          tar -xJf x86_64-cross-tools-loongarch64-binutils_2.43.1-gcc_14.2.0-glibc_2.40.tar.xz
          echo "$PWD/cross-tools/bin" >> "$GITHUB_PATH"
        fi

    - name: Patch GRUB
      run: |
        cd grub
        git apply ../0001-GRUB-fixes.patch
        cd ..

    - name: Build drivers
      run: make ARCH=${{ matrix.arch }} CROSS_COMPILE=${{ matrix.tuple }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'push' }}
      with:
        name: gcc_gnu-efi_${{ matrix.arch }}
        path: src/*.efi

  merge-artifacts:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: gcc_gnu-efi
          delete-merged: true