name: Windows, MSVC, gnu-efi

on: 
  push:
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**.cmd'
      - '!set_grub_cpu.cmd'
      - '**.md'
      - '**.sh'
      - '!set_grub_cpu.sh'
      - '**.txt'
      - '**.vbs'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**.cmd'
      - '!set_grub_cpu.cmd'
      - '**.md'
      - '**.sh'
      - '!set_grub_cpu.sh'
      - '**.txt'
      - '**.vbs'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, ia32, aa64]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Patch GRUB
      run: |
        cd grub
        git apply ..\0001-GRUB-fixes.patch
        cd ..

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build drivers
      run: |
        msbuild efifs.sln /m /p:Configuration=Debug,Platform=${{ matrix.arch }}
        msbuild efifs.sln /m /p:Configuration=Release,Platform=${{ matrix.arch }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'push' }}
      with:
        name: msvc_gnu-efi_${{ matrix.arch }}
        path: ${{ matrix.arch }}/Release/*.efi

  merge-artifacts:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: msvc_gnu-efi
          delete-merged: true